name: Build and Release Just A Sample

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Delete old assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ASSETS=$(gh release view v${{ needs.build.outputs.base_version }}-latest --json assets -q '.assets[].name' || true)
          for asset in $ASSETS; do
            gh release delete-asset v${{ needs.build.outputs.base_version }}-latest "$asset" -y
          done  

      - name: Create or Update Release
        uses: ncipollo/release-action@v1.20.0
        with:
          tag: "v${{ needs.build.outputs.base_version }}-latest"
          name: "Just A Sample v${{ needs.build.outputs.base_version }} Latest"
          artifacts: "artifacts/*"
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          draft: false
          omitBodyDuringUpdate: true

      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          echo "${{ github.workspace }}/butler" >> $GITHUB_PATH

      - name: Publish to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push artifacts/Install.Just.a.Sample.Windows.v${{ needs.build.outputs.full_version }}.zip        binyaminf/just-a-sample:windows-easy-installer    --userversion ${{ needs.build.outputs.full_version }}
          butler push artifacts/Install.Just.a.Sample.macOS.v${{ needs.build.outputs.full_version }}.dmg          binyaminf/just-a-sample:macos-easy-installer      --userversion ${{ needs.build.outputs.full_version }}
          butler push artifacts/JAS.Windows.VST3.v${{ needs.build.outputs.full_version }}.zip                     binyaminf/just-a-sample:windows-vst3              --userversion ${{ needs.build.outputs.full_version }}
          butler push artifacts/JAS.macOS.VST3.v${{ needs.build.outputs.full_version }}.zip                       binyaminf/just-a-sample:macos-vst3                --userversion ${{ needs.build.outputs.full_version }}
          butler push artifacts/JAS.macOS.AU.v${{ needs.build.outputs.full_version }}.zip                         binyaminf/just-a-sample:macos-au                  --userversion ${{ needs.build.outputs.full_version }}
          butler push artifacts/JAS.Linux.VST3.v${{ needs.build.outputs.full_version }}.zip                       binyaminf/just-a-sample:linux-vst3                --userversion ${{ needs.build.outputs.full_version }}